https://en.wikipedia.org/wiki/Kronecker_product

$\mathbf{A}\otimes\mathbf{B} = \begin{bmatrix} a_{11} \mathbf{B} & \cdots & a_{1n}\mathbf{B} \\ \vdots & \ddots & \vdots \\ a_{m1} \mathbf{B} & \cdots & a_{mn} \mathbf{B} \end{bmatrix}$

In [1]:
import tensorflow as tf

In [2]:
sess = tf.InteractiveSession()

In [3]:
x = tf.constant([[1,2,3],
                 [4,5,6]])

In [4]:
tf.expand_dims(x, axis=2).eval()

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]], dtype=int32)

In [5]:
tf.tile(tf.expand_dims(x, axis=2), [1, 1, 2]).eval()

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]], dtype=int32)

In [6]:
tf.reshape(tf.tile(tf.expand_dims(x, axis=2), [1, 1, 2]), [2,6]).eval()

array([[1, 1, 2, 2, 3, 3],
       [4, 4, 5, 5, 6, 6]], dtype=int32)

In [8]:
def kron(_x, _k):
    h = tf.shape(_x)[0]
    return tf.reshape(tf.tile(tf.expand_dims(_x, axis=-1), [1, 1, _k]), [h, -1])

kron(x, 4).eval()

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3],
       [4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6]], dtype=int32)